
export const LOADING_MESSAGES: string[] = [
  "Analyzing A-Level Synergy...",
  "Consulting Russell Group Guidance...",
  "Connecting Subjects to University Courses...",
  "Calculating Future Earnings...",
  "Mapping Career Pathways...",
  "Generating Your Future Story...",
];

export const A_LEVEL_SUBJECTS: string[] = [
  "Accounting",
  "Art and Design",
  "Biology",
  "Business Studies",
  "Chemistry",
  "Classical Civilisation",
  "Computer Science",
  "Design and Technology",
  "Drama and Theatre",
  "Economics",
  "English Language",
  "English Literature",
  "Environmental Science",
  "Film Studies",
  "French",
  "Further Mathematics",
  "Geography",
  "German",
  "Government and Politics",
  "History",
  "Italian",
  "Law",
  "Mandarin",
  "Mathematics",
  "Media Studies",
  "Music",
  "Philosophy",
  "Physical Education",
  "Physics",
  "Psychology",
  "Religious Studies",
  "Sociology",
  "Spanish",
];

export const RUSSELL_GROUP_UNIVERSITIES: string[] = [
  "University of Birmingham",
  "University of Bristol",
  "University of Cambridge",
  "Cardiff University",
  "Durham University",
  "University of Edinburgh",
  "University of Exeter",
  "University of Glasgow",
  "Imperial College London",
  "King's College London",
  "University of Leeds",
  "University of Liverpool",
  "London School of Economics and Political Science",
  "University of Manchester",
  "Newcastle University",
  "University of Nottingham",
  "University of Oxford",
  "Queen Mary University of London",
  "Queen's University Belfast",
  "University of Sheffield",
  "University of Southampton",
  "University College London",
  "University of Warwick",
  "University of York",
];
